# Generated by Django 5.2.6 on 2025-10-27 16:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=200, verbose_name='Producto / Servicio')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Detalle de Orden',
                'verbose_name_plural': 'Detalles de Órdenes',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='N° Orden')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('generada', 'Generada'), ('borrador', 'Borrador'), ('pendiente', 'Pendiente Aprobación'), ('aprobada', 'Aprobada'), ('ejecutada', 'Ejecutada'), ('recibida', 'Recibida'), ('rechazada', 'Rechazada'), ('cerrada', 'Cerrada')], default='borrador', max_length=20)),
                ('destino', models.CharField(choices=[('constructora', 'Constructora'), ('proyecto', 'Proyecto'), ('interna', 'Compra Interna')], default='proyecto', max_length=20, verbose_name='Destino de la orden')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automática')], default='manual', help_text='Manual: creada por usuario. Automática: generada por el sistema', max_length=15, verbose_name='Origen')),
                ('presupuesto_disponible_al_crear', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Presupuesto Disponible al Crear')),
                ('presupuesto_suficiente', models.BooleanField(default=True, verbose_name='Presupuesto Suficiente')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre / Razón Social')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT / Documento')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona de contacto')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
    ]
