# Generated by Django 5.2.6 on 2025-10-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='origen',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automática')], default='manual', help_text='Manual: creada por usuario. Automática: generada por el sistema', max_length=15, verbose_name='Origen'),
        ),
    ]
