# Generated by Django 5.2.6 on 2025-10-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='presupuesto_disponible_al_crear',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot del presupuesto disponible al momento de crear la OC', max_digits=15, null=True, verbose_name='Presupuesto Disponible al Crear'),
        ),
    ]
