# Generated by Django 5.2.6 on 2025-10-27 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_ordencompra_origen'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='presupuesto_compras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='proyectos.presupuestocompras', verbose_name='Presupuesto de Compras'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='presupuesto_disponible_al_crear',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot del presupuesto disponible al momento de crear la OC', max_digits=15, null=True, verbose_name='Presupuesto Disponible al Crear'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='presupuesto_suficiente',
            field=models.BooleanField(default=True, verbose_name='Presupuesto Suficiente'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='proyectos.proyecto', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('generada', 'Generada'), ('borrador', 'Borrador'), ('pendiente', 'Pendiente Aprobación'), ('aprobada', 'Aprobada'), ('ejecutada', 'Ejecutada'), ('recibida', 'Recibida'), ('rechazada', 'Rechazada'), ('cerrada', 'Cerrada')], default='borrador', max_length=20),
        ),
    ]
