# Generated by Django 5.2.6 on 2025-10-20 18:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('responsable', models.CharField(blank=True, max_length=100, verbose_name='Responsable')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad', models.CharField(help_text='Ej: kg, litros, unidades', max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
                ('stock_maximo', models.PositiveIntegerField(default=0)),
                ('iva', models.DecimalField(decimal_places=2, default=19, max_digits=5, verbose_name='IVA (%)')),
                ('descuento_proveedor', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento Proveedor (%)')),
            ],
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=50, unique=True, verbose_name='Serial')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('fecha_compra', models.DateField(blank=True, null=True, verbose_name='Fecha de Compra')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('responsable', models.CharField(blank=True, max_length=100, verbose_name='Responsable')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('asignacion', 'Asignación'), ('devolucion', 'Devolución'), ('baja', 'Baja')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.herramienta')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoKardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacion', models.TextField(blank=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.maquinaria')),
            ],
        ),
    ]