# Generated by Django 5.2.6 on 2025-10-21 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='insumo',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos', to='compras.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='maquinaria',
            name='manual',
            field=models.FileField(blank=True, help_text='Archivo PDF del manual de la maquinaria', null=True, upload_to='manuales/', verbose_name='Manual'),
        ),
    ]
