# Generated by Django 5.2.6 on 2025-10-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='descuento_proveedor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento Proveedor (%)'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=19, max_digits=5, verbose_name='IVA (%)'),
        ),
    ]
