# Generated by Django 5.2.6 on 2025-10-17 21:04

import django.db.models.deletion
import nexusone.administrativa.ordenes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default=nexusone.administrativa.ordenes.models.generar_numero_ot, max_length=5, unique=True, verbose_name='NÃºmero OT')),
                ('descripcion', models.TextField(blank=True, verbose_name='DescripciÃ³n')),
                ('constructora', models.CharField(choices=[('consorcio_alfa', 'Consorcio Alfa'), ('la_riviera', 'La Riviera'), ('maca', 'Maca'), ('torreon', 'Torreon'), ('c_u', 'C&U'), ('plinco', 'Plinco'), ('nucleo', 'Nucleo'), ('urbana', 'Urbana'), ('N/E', 'N/E')], max_length=40, verbose_name='Constructora')),
                ('proyecto', models.CharField(choices=[('ventura', 'Ventura'), ('la_primavera', 'La Primavera'), ('mallorca', 'Mallorca'), ('o2_del_cerro', 'O2 del Cerro'), ('antigua', 'Antigua'), ('monte_real', 'Monte Real'), ('koa', 'Koa Loft'), ('perla nova', 'Perla Nova'), ('Cocinas Pereira', 'Cocinas Pereira'), ('externo', 'Externo')], max_length=40, verbose_name='Proyecto')),
                ('proceso', models.CharField(choices=[('mecanizado', 'Mecanizado'), ('ensamble', 'Ensamble'), ('despacho', 'Despacho')], max_length=20, verbose_name='Proceso')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Apertura')),
                ('fecha_envio', models.DateField(blank=True, null=True, verbose_name='Fecha de EnvÃ\xado')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('en_proceso', 'En proceso'), ('cerrada', 'Cerrada')], default='abierta', max_length=20, verbose_name='Estado')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('cierre_a_tiempo', models.BooleanField(blank=True, null=True, verbose_name='Cierre a Tiempo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nueva_orden', 'Nueva Orden'), ('proxima_envio', 'Próxima a Envío'), ('vencida', 'Orden Vencida'), ('a_tiempo', 'Cerrada a Tiempo'), ('tarde', 'Cerrada Tarde')], max_length=20)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='ordenes.ordentrabajo')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Documento sin nombre', max_length=255)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=nexusone.administrativa.ordenes.models.ruta_documento_ot)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='ordenes.ordentrabajo')),
            ],
        ),
    ]
