# Generated by Django 5.2.6 on 2025-10-27 16:51

import django.db.models.deletion
import nexusone.administrativa.ordenes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default=nexusone.administrativa.ordenes.models.generar_numero_ot, max_length=5, unique=True, verbose_name='Número OT')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('constructora', models.CharField(blank=True, choices=[('consorcio_alfa', 'Consorcio Alfa'), ('asul', 'Asul'), ('maca', 'Maca'), ('torreon', 'Torreon'), ('c_u', 'C&U'), ('plinco', 'Plinco'), ('nucleo', 'Nucleo'), ('urbana', 'Urbana'), ('N/E', 'N/E')], max_length=40, verbose_name='Constructora')),
                ('proyecto', models.CharField(blank=True, choices=[('ventura', 'Ventura'), ('la_primavera', 'La Primavera'), ('mallorca', 'Mallorca'), ('o2_del_cerro', 'O2 del Cerro'), ('antigua', 'Antigua'), ('montreal', 'MontReal'), ('koa', 'Koa Loft'), ('perla nova', 'Perla Nova'), ('riviera verde', 'Riviera Verde Etp 1'), ('Cocinas Pereira', 'Cocinas Pereira'), ('externo', 'Externo'), ('sala de ventas', 'Sala de Ventas'), ('apto modelo', 'Apto Modelo')], max_length=40, verbose_name='Proyecto')),
                ('proceso', models.CharField(choices=[('mecanizado', 'Mecanizado'), ('ensamble', 'Ensamble'), ('despacho', 'Despacho')], max_length=20, verbose_name='Proceso')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Apertura')),
                ('fecha_envio', models.DateField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('abierta', 'Abierta'), ('en_proceso', 'En proceso'), ('pausada', 'Pausada'), ('cerrada', 'Cerrada')], default='abierta', max_length=20, verbose_name='Estado')),
                ('cierre_a_tiempo', models.BooleanField(blank=True, null=True, verbose_name='Cierre a Tiempo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automática')], default='manual', help_text='Manual: creada por usuario. Automática: generada por el sistema', max_length=15, verbose_name='Origen')),
                ('cantidad_producir', models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad total a producir (solo para OTs automáticas)', max_digits=10, null=True, verbose_name='Cantidad a Producir')),
                ('cantidad_producida', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad Producida')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridad')),
                ('fecha_inicio_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Inicio Real')),
                ('entrega_programada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to='proyectos.entregaprogramada', verbose_name='Entrega Programada')),
                ('item_contratado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to='proyectos.itemcontratado', verbose_name='Item Contratado')),
                ('orden_dependiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_dependientes_de_esta', to='ordenes.ordentrabajo', verbose_name='Depende de OT')),
                ('proyecto_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to='proyectos.proyecto', verbose_name='Proyecto Vinculado')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nueva_orden', 'Nueva Orden'), ('proxima_envio', 'Próxima a Envío'), ('vencida', 'Orden Vencida'), ('a_tiempo', 'Cerrada a Tiempo'), ('tarde', 'Cerrada Tarde')], max_length=20)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='ordenes.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Documento sin nombre', max_length=255)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=nexusone.administrativa.ordenes.models.ruta_documento_ot)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='ordenes.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Documento de Orden',
                'verbose_name_plural': 'Documentos de Órdenes',
            },
        ),
    ]
