# Generated by Django 5.2.6 on 2025-10-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='proyecto',
            field=models.CharField(choices=[('ventura', 'Ventura'), ('la_primavera', 'La Primavera'), ('mallorca', 'Mallorca'), ('o2_del_cerro', 'O2 del Cerro'), ('antigua', 'Antigua'), ('monte_real', 'Monte Real'), ('koa', 'Koa Loft'), ('perla nova', 'Perla Nova'), ('Cocinas Pereira', 'Cocinas Pereira'), ('externo', 'Externo'), ('sala de ventas', 'Sala de Ventas'), ('apto modelo', 'Apto Modelo')], max_length=40, verbose_name='Proyecto'),
        ),
    ]
