# Generated by Django 5.2.6 on 2025-10-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_alter_ordentrabajo_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='constructora',
            field=models.CharField(choices=[('consorcio_alfa', 'Consorcio Alfa'), ('asul', 'Asul'), ('maca', 'Maca'), ('torreon', 'Torreon'), ('c_u', 'C&U'), ('plinco', 'Plinco'), ('nucleo', 'Nucleo'), ('urbana', 'Urbana'), ('N/E', 'N/E')], max_length=40, verbose_name='Constructora'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='proyecto',
            field=models.CharField(choices=[('ventura', 'Ventura'), ('la_primavera', 'La Primavera'), ('mallorca', 'Mallorca'), ('o2_del_cerro', 'O2 del Cerro'), ('antigua', 'Antigua'), ('montreal', 'MontReal'), ('koa', 'Koa Loft'), ('perla nova', 'Perla Nova'), ('riviera verde', 'Riviera Verde Etp 1'), ('Cocinas Pereira', 'Cocinas Pereira'), ('externo', 'Externo'), ('sala de ventas', 'Sala de Ventas'), ('apto modelo', 'Apto Modelo')], max_length=40, verbose_name='Proyecto'),
        ),
    ]
