# Generated by Django 5.2.6 on 2025-10-07 21:05

import nexusone.administrativa.ordenes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_alter_documentoorden_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoorden',
            name='drive_download_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentoorden',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documentoorden',
            name='drive_view_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentoorden',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=nexusone.administrativa.ordenes.models.ruta_documento_ot),
        ),
    ]
