# Generated by Django 5.2.6 on 2025-10-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_alter_ordentrabajo_constructora_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoorden',
            options={'verbose_name': 'Documento de Orden', 'verbose_name_plural': 'Documentos de Órdenes'},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='ordentrabajo',
            options={'ordering': ['-fecha_apertura'], 'verbose_name': 'Orden de Trabajo', 'verbose_name_plural': 'Órdenes de Trabajo'},
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='cantidad_producida',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad Producida'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='cantidad_producir',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad total a producir (solo para OTs automáticas)', max_digits=10, null=True, verbose_name='Cantidad a Producir'),
        ),
    ]
