# Generated by Django 5.2.6 on 2025-10-27 16:11

import django.db.models.deletion
import nexusone.administrativa.ordenes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_alter_documentoorden_options_and_more'),
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='entrega_programada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to='proyectos.entregaprogramada', verbose_name='Entrega Programada'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_inicio_real',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Inicio Real'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='item_contratado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to='proyectos.itemcontratado', verbose_name='Item Contratado'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='orden_dependiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_dependientes_de_esta', to='ordenes.ordentrabajo', verbose_name='Depende de OT'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='origen',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automática')], default='manual', help_text='Manual: creada por usuario. Automática: generada por el sistema', max_length=15, verbose_name='Origen'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridad'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='proyecto_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to='proyectos.proyecto', verbose_name='Proyecto Vinculado'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='constructora',
            field=models.CharField(blank=True, choices=[('consorcio_alfa', 'Consorcio Alfa'), ('asul', 'Asul'), ('maca', 'Maca'), ('torreon', 'Torreon'), ('c_u', 'C&U'), ('plinco', 'Plinco'), ('nucleo', 'Nucleo'), ('urbana', 'Urbana'), ('N/E', 'N/E')], max_length=40, verbose_name='Constructora'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('abierta', 'Abierta'), ('en_proceso', 'En proceso'), ('pausada', 'Pausada'), ('cerrada', 'Cerrada')], default='abierta', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fecha_envio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Envío'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='numero',
            field=models.CharField(default=nexusone.administrativa.ordenes.models.generar_numero_ot, max_length=5, unique=True, verbose_name='Número OT'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='proyecto',
            field=models.CharField(blank=True, choices=[('ventura', 'Ventura'), ('la_primavera', 'La Primavera'), ('mallorca', 'Mallorca'), ('o2_del_cerro', 'O2 del Cerro'), ('antigua', 'Antigua'), ('montreal', 'MontReal'), ('koa', 'Koa Loft'), ('perla nova', 'Perla Nova'), ('riviera verde', 'Riviera Verde Etp 1'), ('Cocinas Pereira', 'Cocinas Pereira'), ('externo', 'Externo'), ('sala de ventas', 'Sala de Ventas'), ('apto modelo', 'Apto Modelo')], max_length=40, verbose_name='Proyecto'),
        ),
    ]
