# Generated by Django 5.2.6 on 2025-10-27 16:11

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0003_add_manual_field_to_maquinaria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Constructora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contacto', models.CharField(blank=True, max_length=100, verbose_name='Persona de Contacto')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Constructora',
                'verbose_name_plural': 'Constructoras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='APU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código APU')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('categoria', models.CharField(choices=[('closet_principal', 'Closet Alcoba Principal'), ('closet_auxiliar', 'Closet Alcoba Auxiliar'), ('cocina_integral', 'Cocina Integral'), ('mueble_bano', 'Mueble de Baño'), ('mueble_tv', 'Mueble de TV'), ('otro', 'Otro')], default='otro', max_length=30, verbose_name='Categoría')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='apu_imagenes/', verbose_name='Imagen')),
                ('factor_venta', models.DecimalField(decimal_places=2, default=Decimal('1.80'), help_text='Multiplicador sobre el costo (ej: 1.80 = 80% de utilidad)', max_digits=5, verbose_name='Factor de Venta')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apus_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'APU',
                'verbose_name_plural': 'APUs',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='APUManoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('fabrica', 'Fabricación en Taller'), ('instalacion', 'Instalación en Obra')], max_length=20, verbose_name='Tipo')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('horas', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Horas')),
                ('tarifa_hora', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarifa por Hora')),
                ('apu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mano_obra', to='proyectos.apu', verbose_name='APU')),
            ],
            options={
                'verbose_name': 'Mano de Obra de APU',
                'verbose_name_plural': 'Mano de Obra de APU',
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='borrador', max_length=20, verbose_name='Estado')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión')),
                ('fecha_validez', models.DateField(blank=True, null=True, verbose_name='Fecha de Validez')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('aprobada_por', models.CharField(blank=True, max_length=100, verbose_name='Aprobada Por')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, help_text='Descuento en pesos o porcentaje', max_digits=12, verbose_name='Descuento')),
                ('ordenes_generadas', models.BooleanField(default=False, verbose_name='Órdenes de Compra Generadas')),
                ('fecha_generacion_ordenes', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Generación OCs')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ItemCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('apu', models.ForeignKey(blank=True, help_text='Si se basa en un APU', null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.apu', verbose_name='APU')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proyectos.cotizacion', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Item de Cotización',
                'verbose_name_plural': 'Items de Cotización',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Proyecto')),
                ('ubicacion', models.CharField(blank=True, max_length=300, verbose_name='Ubicación')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('cotizacion', 'En Cotización'), ('aprobado', 'Aprobado'), ('en_ejecucion', 'En Ejecución'), ('pausado', 'Pausado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='cotizacion', max_length=20, verbose_name='Estado')),
                ('estado_financiero', models.CharField(choices=[('pendiente', 'Pendiente Anticipo'), ('anticipo_recibido', 'Anticipo Recibido'), ('en_cortes', 'En Cortes'), ('liquidado', 'Liquidado')], default='pendiente', max_length=30, verbose_name='Estado Financiero')),
                ('porcentaje_avance', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Avance')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha Fin Estimada')),
                ('fecha_fin_real', models.DateField(blank=True, null=True, verbose_name='Fecha Fin Real')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Total')),
                ('valor_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Pagado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('constructora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='proyectos.constructora', verbose_name='Constructora')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='PresupuestoCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anticipo_base', models.DecimalField(decimal_places=2, help_text='Monto del anticipo recibido', max_digits=15, verbose_name='Anticipo Base')),
                ('porcentaje_asignado', models.DecimalField(decimal_places=2, default=80, help_text='% del anticipo destinado a compras', max_digits=5, verbose_name='Porcentaje Asignado')),
                ('monto_asignado', models.DecimalField(decimal_places=2, editable=False, max_digits=15, verbose_name='Monto Asignado')),
                ('monto_disponible', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Disponible')),
                ('monto_comprometido', models.DecimalField(decimal_places=2, default=0, help_text='OCs pendientes de ejecutar', max_digits=15, verbose_name='Monto Comprometido')),
                ('monto_ejecutado', models.DecimalField(decimal_places=2, default=0, help_text='OCs ya pagadas', max_digits=15, verbose_name='Monto Ejecutado')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('asignado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Asignado Por')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos_compras', to='proyectos.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Presupuesto de Compras',
                'verbose_name_plural': 'Presupuestos de Compras',
            },
        ),
        migrations.CreateModel(
            name='ItemContratado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200, verbose_name='Item')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('unidad', models.CharField(default='und', max_length=20, verbose_name='Unidad')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Unitario')),
                ('es_manual', models.BooleanField(default=False, verbose_name='Es Manual')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('apu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.apu', verbose_name='APU')),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.cotizacion', verbose_name='Cotización Origen')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.insumo', verbose_name='Insumo Relacionado')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proyectos.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Item Contratado',
                'verbose_name_plural': 'Items Contratados',
            },
        ),
        migrations.CreateModel(
            name='EntregaProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_entrega', models.PositiveIntegerField(verbose_name='Número de Entrega')),
                ('fecha_requerida', models.DateField(verbose_name='Fecha Requerida por Cliente')),
                ('fecha_real', models.DateField(blank=True, null=True, verbose_name='Fecha Real de Entrega')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_produccion', 'En Producción'), ('lista', 'Lista para Despacho'), ('despachada', 'Despachada'), ('cerrada', 'Cerrada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='proyectos.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Entrega Programada',
                'verbose_name_plural': 'Entregas Programadas',
                'ordering': ['proyecto', 'numero_entrega'],
                'unique_together': {('proyecto', 'numero_entrega')},
            },
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='proyectos.proyecto', verbose_name='Proyecto'),
        ),
        migrations.CreateModel(
            name='Anticipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('anticipo_inicial', 'Anticipo Inicial'), ('corte_1', 'Corte 1'), ('corte_2', 'Corte 2'), ('corte_3', 'Corte 3'), ('liquidacion', 'Liquidación Final')], max_length=20, verbose_name='Tipo')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='% del valor total del proyecto', max_digits=5, verbose_name='Porcentaje')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('condicion', models.CharField(blank=True, help_text='Ej: Al 40% de avance', max_length=200, verbose_name='Condición')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('recibido', 'Recibido'), ('aplicado', 'Aplicado al Proyecto')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_esperada', models.DateField(blank=True, null=True, verbose_name='Fecha Esperada')),
                ('fecha_recibido', models.DateField(blank=True, null=True, verbose_name='Fecha Recibido')),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='anticipos/', verbose_name='Comprobante')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anticipos', to='proyectos.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Anticipo',
                'verbose_name_plural': 'Anticipos',
                'ordering': ['proyecto', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='APUMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Cantidad Requerida')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio snapshot del insumo al momento de crear el APU', max_digits=12, verbose_name='Precio Unitario')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('apu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='proyectos.apu', verbose_name='APU')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.insumo', verbose_name='Insumo')),
            ],
            options={
                'verbose_name': 'Material de APU',
                'verbose_name_plural': 'Materiales de APU',
                'unique_together': {('apu', 'insumo')},
            },
        ),
        migrations.CreateModel(
            name='ItemEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('cantidad_producida', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad Producida')),
                ('cantidad_despachada', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad Despachada')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proyectos.entregaprogramada', verbose_name='Entrega')),
                ('item_contratado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.itemcontratado', verbose_name='Item Contratado')),
            ],
            options={
                'verbose_name': 'Item de Entrega',
                'verbose_name_plural': 'Items de Entrega',
                'unique_together': {('entrega', 'item_contratado')},
            },
        ),
    ]
