# Generated by Django 5.2.6 on 2025-10-24 16:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constructora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(help_text='Nombre legal de la constructora', max_length=200, unique=True, verbose_name='Razón Social')),
                ('nit', models.CharField(help_text='Formato: 123456789-0', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de NIT inválido. Debe ser: 123456789-0', regex='^\\d{9,10}-\\d{1}$')], verbose_name='NIT')),
                ('telefono', models.CharField(help_text='Ej: +57 311 1234567', max_length=15, validators=[django.core.validators.RegexValidator(message='Número de teléfono inválido', regex='^\\+?[\\d\\s-]{7,15}$')], verbose_name='Teléfono')),
                ('ubicacion', models.CharField(help_text='Dirección de oficina principal', max_length=300, verbose_name='Ubicación')),
                ('correo', models.EmailField(help_text='Email de contacto principal', max_length=254, verbose_name='Correo Electrónico')),
                ('representante_legal', models.CharField(blank=True, help_text='Nombre del representante legal', max_length=150, verbose_name='Representante Legal')),
                ('contacto_adicional', models.TextField(blank=True, help_text='Otros teléfonos, emails o contactos importantes', verbose_name='Información de Contacto Adicional')),
                ('observaciones', models.TextField(blank=True, help_text='Notas generales sobre la constructora', verbose_name='Observaciones')),
                ('activa', models.BooleanField(default=True, verbose_name='Constructora Activa')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Constructora',
                'verbose_name_plural': 'Constructoras',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del proyecto', max_length=200, verbose_name='Nombre del Proyecto')),
                ('tipo_proyecto', models.CharField(choices=[('vis', 'VIS - Vivienda de Interés Social'), ('vip', 'VIP - Vivienda de Interés Prioritario'), ('apto_modelo', 'Apartamento Modelo'), ('casa', 'Casa'), ('apartamentos', 'Apartamentos'), ('secciones', 'Secciones'), ('torre_1', 'Torre 1'), ('torre_2', 'Torre 2'), ('torre_3', 'Torre 3'), ('torre_4', 'Torre 4'), ('ala_a', 'Ala A'), ('ala_b', 'Ala B'), ('etapa_1', 'Etapa 1'), ('etapa_2', 'Etapa 2'), ('otro', 'Otro')], default='apartamentos', max_length=20, verbose_name='Tipo de Proyecto')),
                ('codigo', models.CharField(help_text='Código único de identificación (ej: PROJ-2025-001)', max_length=50, unique=True, verbose_name='Código del Proyecto')),
                ('ubicacion_proyecto', models.CharField(help_text='Dirección donde se ejecuta el proyecto', max_length=300, verbose_name='Ubicación del Proyecto')),
                ('contrato', models.FileField(blank=True, help_text='Archivo PDF del contrato', null=True, upload_to='contratos/', verbose_name='Contrato (PDF)')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización Estimada')),
                ('fecha_fin_real', models.DateField(blank=True, help_text='Fecha real de finalización del proyecto', null=True, verbose_name='Fecha de Finalización Real')),
                ('estado', models.CharField(choices=[('planeacion', 'Planeación'), ('en_curso', 'En Curso'), ('pausado', 'Pausado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='planeacion', max_length=20, verbose_name='Estado')),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, help_text='Presupuesto total del proyecto', max_digits=15, null=True, verbose_name='Presupuesto')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del proyecto', verbose_name='Descripción')),
                ('numero_unidades', models.PositiveIntegerField(blank=True, help_text='Cantidad de apartamentos, casas, etc.', null=True, verbose_name='Número de Unidades')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre el proyecto', verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Proyecto Activo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('constructora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='proyectos.constructora', verbose_name='Constructora')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-creado'],
            },
        ),
    ]
