# Generated by Django 5.2.6 on 2025-10-24 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemContratado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(help_text='Nombre del ítem contratado', max_length=200, verbose_name='Item')),
                ('medida', models.CharField(help_text='Ej: m², m³, unidad, kg, etc.', max_length=50, verbose_name='Unidad de Medida')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad contratada', max_digits=10, verbose_name='Cantidad')),
                ('valor_unitario', models.DecimalField(decimal_places=2, help_text='Valor por unidad', max_digits=15, verbose_name='Valor Unitario')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_contratados', to='proyectos.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Item Contratado',
                'verbose_name_plural': 'Items Contratados',
                'ordering': ['creado'],
            },
        ),
    ]
